version: "3"
services:
  scheduler:
    image: ghcr.io/reddec/compose-scheduler:1.0.2
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  imdb-exporter:
    image: imdb-exporter:latest
    init: true
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app:z
    labels:
      net.reddec.scheduler.cron: "@daily"
